name: Cypress Try

on: [push]

jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Cypress run
        run: npm test

      - name: Runs ESlint
        run: npm run lint
