name: Cypress Try
on: [push]
jobs:
  eslint:
    name: lint code base
    runs-on: ubuntu-latest
  cypress-run: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Install packages
        uses: npm Install
      - name: Cypress run
        uses: npm test
